spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/yyc-security?useUnicode=true&characterEncoding=utf8
    username: root
    password: root
  session:
    store-type: none
#security:
#  basic:
#    enabled: false
yyc:
  security:
    browserProperties:
      defaultReturnUrl: /auth